--Asesores
INSERT INTO ASE_ASESORES(NV_NOMBRE,NV_ESPECIALIDAD) VALUES('Asesor 1', 'Especialidad A');
INSERT INTO ASE_ASESORES(NV_NOMBRE,NV_ESPECIALIDAD) VALUES('Asesor 2', 'Especialidad B');
INSERT INTO ASE_ASESORES(NV_NOMBRE,NV_ESPECIALIDAD) VALUES('Asesor 3', 'Especialidad C');
